### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by sashulyak** [ChaunceyKiwi/image-matting#2]
Hi!

I'm trying to run your code, but got the error:

`dyld: Library not loaded: /Users/Chauncey/Downloads/SuiteSparse/lib/libamd.2.4.6.dylib
  Referenced from: /Users/sashulyak/Repos/imageMatting/code/make/./imageMatting
  Reason: image not found
Abort trap: 6`

Did you hardcode the path somewhere in binary files? Cannot find it in sources.

**Comment by ChaunceyKiwi** [comment]
Install `SuiteSparse.tar.gz` from http://faculty.cse.tamu.edu/davis/suitesparse.html and unzip it to the directory /imageMatting/code, and run following instructions to install library:
``
cd imageMatting/SuiteSparse
make library
``

Pull my newest commit and please let me know if it still does not work :)

**Comment by ChaunceyKiwi** [comment]
Install SuiteSparse.tar.gz from http://faculty.cse.tamu.edu/davis/suitesparse.html, unzip it to the directory `/imageMatting/code`. 

Run following instructions to install library:  
`cd imageMatting/code/SuiteSparse; make library;`

Remember to pull my latest commit and please let me know if it still does not work :)

**Comment by sashulyak** [comment]
Thanks, man! Works well now! =)
